[tool.poetry]
name = "assertioncommander"
version = "0.1.0"
description = ""
authors = ["sprimbs <53371440+sprimbs@users.noreply.github.com>"]
readme = "README.md"
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.10"
evaluate = "^0.4.1"
scikit-learn = "^1.3.2"
black = "^23.12.1"
urllib3 = "^1.26.12"
nltk = "^3.8.1"
tqdm = "^4.66.1"
isort = { version = "~5.13.0", extras = ["pyproject"] }
ruff = "~0.1.0"
transformers = "^4.37.2"
torch = "^2.2.0"
bidict = "^0.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
indent = "    "

[tool.black]
line-length = 88
target_version = ["py310"]
include = '\.pyi?$'


[tool.ruff]
line-length = 88
select = ["ALL"]
# base set of ignored rules, to be adapted as needed
# https://beta.ruff.rs/docs/rules/
ignore = [
    "ANN003", # typing annotations for kwargs, self, cls not needed
    "ANN101",
    "ANN102",
    "COM", # trailing commas -> black
    "D", # documentation
    "E", # code style -> black
    "EXE002", # executable files must not specify a shebang
    "I", # import order -> isort
    "ISC",
    "T20", # allow print statements
    "PLR",
    "RUF013",
    "S113",
    "S603",
    "BLE001"
]
show-source = true
exclude = [
    "docs",
    ".venv",
    "venv",
    ".mypy_cache",
    ".pytest_cache",
]
target-version = "py310"
[tool.poetry.scripts]
evaluate = "src.main:run"